# Generated by Django 4.0.5 on 2022-09-27 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='emissao',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
    ]
