# Generated by Django 4.0.5 on 2022-09-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_cpf_clientes_email_clientes_estado_and_more'),
        ('vendas', '0002_alter_vendas_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendascliente', to='clientes.clientes'),
        ),
    ]
