# Generated by Django 4.0.5 on 2022-12-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_vendas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpo_venda',
            name='desconto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='emissao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
