# Generated by Django 4.0.5 on 2022-12-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financiamento',
            old_name='emissao',
            new_name='dt_emissao',
        ),
        migrations.RenameField(
            model_name='financiamento',
            old_name='vencimento',
            new_name='dt_vencimento',
        ),
        migrations.AddField(
            model_name='financiamento',
            name='dt_baixa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('B', 'Baixado'), ('P', 'Parcial')], default='A', max_length=1),
        ),
    ]
