# Generated by Django 4.0.5 on 2022-09-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('custo_un', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_categoria', to='produtos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_marca', to='produtos.marca')),
            ],
        ),
    ]
