# Generated by Django 4.0.5 on 2022-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imggrande',
            field=models.ImageField(blank=True, null=True, upload_to='imggrande'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='imgpequena',
            field=models.ImageField(blank=True, null=True, upload_to='imgpequena'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
