# Generated by Django 4.0.5 on 2023-03-31 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produto_modelo', to='produtos.modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='tamanho',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='produto_tamanho', to='produtos.tamanho'),
            preserve_default=False,
        ),
    ]
