# Generated by Django 4.0.5 on 2023-03-31 15:06

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_modelo_tamanho_produtos_modelo_produtos_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='hash_imagem',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=produtos.models.nome_arquivo_imagem),
        ),
        migrations.AddField(
            model_name='produtos',
            name='imagem_miniatura',
            field=models.ImageField(blank=True, upload_to=produtos.models.nome_arquivo_imagem_miniatura),
        ),
    ]
