# Generated by Django 4.0.5 on 2023-03-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produtos_hash_imagem_alter_produtos_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='imagem_miniatura',
        ),
    ]
