# Generated by Django 4.0.5 on 2023-03-31 17:45

from django.db import migrations
import imagekit.models.fields
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produtos_imagem_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem_miniatura',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=produtos.models.nome_arquivo_imagem_miniatura),
            preserve_default=False,
        ),
    ]
